# Generated by Django 5.0.6 on 2024-06-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='todo_list',
            new_name='TodoList',
        ),
    ]
