ALTER TABLE tasks ADD COLUMN prioridade VARCHAR(20) NOT NULL DEFAULT 'MEDIA';
ALTER TABLE tasks ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'A_FAZER';
ALTER TABLE tasks ADD COLUMN categoria VARCHAR(30) NOT NULL DEFAULT 'GERAL';
ALTER TABLE tasks ADD COLUMN data_vencimento DATE;
ALTER TABLE tasks ADD COLUMN deletada BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN data_delecao DATETIME;

CREATE TABLE subtasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    data_criacao DATETIME NOT NULL,
    CONSTRAINT fk_subtask_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);
