ALTER TABLE tasks ADD COLUMN pomodoros_estimados INT NOT NULL DEFAULT 1;
ALTER TABLE tasks ADD COLUMN pomodoros_realizados INT NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN recorrencia VARCHAR(20) NOT NULL DEFAULT 'NENHUMA';
